Routers/woegoru
phialka/server pull request #5
Opened 2022-11-30 08:23 UTC by woegoru

2022-11-30 13:24 UTC, ogolknev reviewed
в общем все хорошо. думаю доработки без контроллеров не жизненная необходимость

2022-11-30 13:24 UTC, ogolknev commented on app/routers/channels.py
> +async def get_list(info: schemas.Channel):
думаю можно доработать параметры функций. и наверное стоит сделать нужные схемы (как я понял схем используемых здесь пока не существует.

2022-11-30 13:24 UTC, ogolknev commented on app/routers/channels.py
> +async def get_list(info: schemas.Channel):
еще туда же ответы на запросы. но наверное пока нет контроллеров и нет смысла с этим особо заморачиваться.

2022-11-30 15:03 UTC, vgorbikov commented on app/routers/channels.py
> +async def get_list(info: schemas.Channel):
> еще туда же ответы на запросы. но наверное пока нет контроллеров и нет смысла с этим особо заморачиваться.

хз, в принципе ничего не мешает схемы сразу добавить

2022-11-30 15:03 UTC, vgorbikov commented on app/routers/channels.py
> +async def get_list(info: schemas.Channel):
да к тому же как это так - схемы используются, но их пока нет... не пойдёт, не запустится

2022-11-30 20:21 UTC, vgorbikov requested changes

2022-11-30 20:21 UTC, vgorbikov commented on app/routers/channels.py
> +async def get_info_channel(info: schemas.Channel):
В пути объявлен параметр пути channel_id, но в функцию он не передаётся. 
Следует добавить его следующим образом
```suggestion
async def get_info_channel(channel_id: int, info: schemas.Channel):

```

2022-11-30 20:21 UTC, vgorbikov commented on app/routers/channels.py
> +async def edit_info_channel(info: schemas.Channel):
Опять же, объявленный в пути параметр не передан в функцию.
Далее по коду это также встречается, отдельно отмечать не буду.

2022-11-30 20:21 UTC, vgorbikov commented on app/routers/channels.py
> +async def edit_info_channel(info: schemas.Channel):
К тому же схема Channel не подходит для описания параметров, требуемых на вход. Ты путаешь входные и возвращаемые параметры. В схеме, nребующейся на вход, должны присутствовать только 2 параметра: title и description.
Также данный эндпоинт принимает параметр photo, который передаётся как бинарный объект и его следует объявить таким образом
```suggestion
async def edit_info_channel(photo: UploadFile, info: schemas.Channel):
```
Класс UploadFile предварительно импортируется из fastapi

2022-12-02 16:24 UTC, vgorbikov commented on app/routers/channels.py
> +async def create_posts(channel_id: int, content: object):
```python
async def create_posts(channel_id: int, content: object):
```
Тип object не описывает конкретной структуры данных, ожидаемой для получения функцией. В соответствии с документацией FastAPI, вместо object следует передать в качестве параметра класс, где с помощью pydantic и аннотаций типов описаны параметры, которые данный эндпоинт ожидает в теле запроса. 
В нашем проекте такие классы мы объявляем в файле schemas.py

2022-12-04 13:54 UTC, ogolknev commented on app/schemas.py
> +class Channel_Role(BaseModel):
Наверное стоит назвать ChannelRole, везде называлось без "_" а тут вдруг так, да и впринципе так классы не называют насколько знаю
```suggestion
class ChannelRole(BaseModel):
```

2022-12-04 14:04 UTC, ogolknev commented on app/routers/channels.py
> +async def create_channel(title: str, description: str, photo: UploadFile):
как писал вадим важно не забывать импортировать данный класс UploadFile

2022-12-04 14:08 UTC, ogolknev commented on app/routers/channels.py
> +from fastapi import APIRouter
```suggestion
from fastapi import APIRouter, UploadFile

```

2022-12-04 14:13 UTC, merged