added database models
phialka/server pull request #6
Opened 2022-11-30 08:25 UTC by woegoru

2022-11-30 11:04 UTC, vgorbikov commented on app/dbmodels.py
> +    conversation_id: int = ormar.Integer()
То есть будем иметь что-то вроде того:
`conversation_id: int = ormar.ForeignKey(Conversation)`
Правда очевидная проблема заключается в том, что модель Conversation добавлял Никита в своей ветке... 
Потому было бы странно брать здесь в качестве внешнего ключа несуществующий класс.

2022-11-30 13:05 UTC, ogolknev commented on app/dbmodels.py
> +    conversation_id: int = ormar.Integer()
думаю ничего страшного не будет если прописать внешний ключ заранее

2022-11-30 20:01 UTC, vgorbikov requested changes

2022-11-30 20:01 UTC, vgorbikov commented on app/dbmodels.py
> +    conversation_id: = Conversation = ormar.ForeignKey(Conversation)
```suggestion
    conversation_id:  Conversation = ormar.ForeignKey(Conversation)
```
Тут закралось лишнее равно))

2022-12-02 16:10 UTC, vgorbikov approved these changes

2022-12-02 16:33 UTC, merged